fixing rc file install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,44 +1,72 @@
 #!/usr/bin/env bash
 
-[ $(uname) = "Linux" ] && apt update && apt upgrade -y && export PKGMGR=apt
+[ $(uname) = "Linux" ] && apt update && export PKGMGR=apt
 [ $(uname) = "Darwin" ] && \
   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && \
   export PKGMGR=brew
 
-packages="bat fzf jq most pipx ripgrep tmux tree wget zsh"
+declare -a packages=(
+  bat
+  fzf
+  jq
+  most
+  pipx
+  ripgrep
+  tmux
+  tree
+  wget
+  zsh
+)
 
 if [ -z "${PKGMGR}" ]; then
   echo "Unsupported OS. Please install Homebrew or apt."
   exit 1
 elif [ "${PKGMGR}" = "apt" ]; then
-  sudo "${PKGMGR}" install -y --no-install-recommends "${packages}" || {
+  sudo "${PKGMGR}" install -y --no-install-recommends "${packages[@]}" || {
     echo "Failed to install some packages with ${PKGMGR}."
   }
 elif [ "${PKGMGR}" = "brew" ]; then
-  ${PKGMGR} install "${packages}" || {
+  ${PKGMGR} install "${packages[@]}" || {
     echo "Failed to install some packages with ${PKGMGR}."
   }
 fi
 
 git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
-source ~/.zshrc
 
-pipx_installs="pre-commit detect-secrets"
+declare -a pipx_installs=(
+  pre-commit
+  detect-secrets
+)
 
-pipx install "${pipx_installs}"
-echo "Ensuring workspace id ${DEVPOD_WORKSPACE_ID} is protected by detect-secrets"
-[ -f "/workspaces/${DEVPOD_WORKSPACE_NAME}/.pre-commit-config.yaml" ] || \
-  cp /home/${USER}/dotfiles/.pre-commit-config.yaml /workspaces/${DEVPOD_WORKSPACE_NAME}
-pre-commit autoupdate && pre-commit install --install-hooks
-[ -f "/workspaces/${DEVPOD_WORKSPACE_NAME}/.secrets.baseline" ] || \
-  detect-secrets scan --all-files > /workspaces/${DEVPOD_WORKSPACE_NAME}/.secrets.baseline
+pipx install "${pipx_installs[@]}"
 
-dotfiles=".zshrc .oh-my-zsh .vimrc .gitconfig .p10k.zsh .terraformrc .tmux.conf"
+if [ -d "/workspaces/${DEVPOD_WORKSPACE_ID}" ]; then
+  cd "/workspaces/${DEVPOD_WORKSPACE_ID}" || exit
+  echo "Detected Codespaces or Devpod environment."
+  echo "Ensuring workspace id ${DEVPOD_WORKSPACE_ID} is protected by detect-secrets and pre-commit."
+  [ -f "/workspaces/${DEVPOD_WORKSPACE_ID}/.pre-commit-config.yaml" ] || { \
+    cp /home/${USER}/dotfiles/.pre-commit-config.yaml /workspaces/${DEVPOD_WORKSPACE_NAME} || \
+    echo "No precommit config found in dotfiles." && \
+    pre-commit autoupdate && pre-commit install --install-hooks
+  }
+  [ -f "/workspaces/${DEVPOD_WORKSPACE_ID}/.secrets.baseline" ] || \
+    detect-secrets scan --all-files > /workspaces/${DEVPOD_WORKSPACE_NAME}/.secrets.baseline
+
+declare -a dotfiles=(
+  .zshrc
+  .oh-my-zsh
+  .gitconfig
+  .p10k.zsh
+  .terraformrc
+  .tmux.conf
+)
 
 for df in "$dotfiles[@]"; do
   echo "Copying dotfile/dotdir ${df}"
-  cp -r "dotfiles/${df}" "${HOME}/"
+  cp -r "dotfiles/${df}" "${HOME}/" || echo "Either ${df} not found in dotfiles or copy failed."
 done
+
+source "${HOME}/.zshrc"
 
 mkdir -p "${HOME}/.config/"
 [ -d "./nvim" ] && cp -r ./nvim "${HOME}/.config/"
